robertbot:

  # Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint4
      - joint7
      - joint10
      - joint13
      

  # Gripper Trajectory Controllers ---------------------------------------
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint18
      - joint22
      

