arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint4
    - joint7
    - joint10
    - joint13
  gains:
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint18
    - joint22
  gains:
    joint18:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint22:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

controller_list:
  - name: robertbot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint4
      - joint7
      - joint10
      - joint13
  - name: robertbot/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint18
      - joint22
